import toothgelImg from '@/assets/products/toothgel.jpeg';
import deodorantImg from '@/assets/products/deodorant.jpeg';
import msmGelImg from '@/assets/products/msm-gel.jpeg';
import aloeGellyImg from '@/assets/products/aloe-gelly.jpeg';
import heatLotionImg from '@/assets/products/heat-lotion.jpeg';
import aloeLipsImg from '@/assets/products/aloe-lips.jpeg';
import moisturizingLotionImg from '@/assets/products/moisturizing-lotion.jpeg';
import conditionerImg from '@/assets/products/conditioner.jpeg';
import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Forever Bright Toothgel',
    slug: 'forever-bright-toothgel',
    description: 'A gentle, non-fluoride toothgel with aloe vera and bee propolis for a naturally bright smile.',
    price: 12.99,
    discountPrice: 9.99,
    stock: 50,
    category: 'personal-care',
    brand: 'Forever Living',
    form: 'gel',
    tags: ['Fluoride-free', 'Natural', 'Vegan'],
    images: [toothgelImg],
    ingredients: ['Aloe Vera Gel', 'Bee Propolis', 'Sodium Lauryl Sulfate', 'Natural Mint'],
    benefits: ['Whitens teeth naturally', 'Freshens breath', 'Gentle on gums', 'Contains no fluoride'],
    dosage: 'Apply to toothbrush and brush twice daily.',
    warnings: ['For external use only', 'Keep out of reach of children'],
    allergens: ['Bee products'],
    ratingAvg: 4.8,
    ratingCount: 234,
    createdAt: '2024-01-15',
    isBestseller: true,
  },
  {
    id: '2',
    name: 'Aloe Ever-Shield Deodorant',
    slug: 'aloe-ever-shield-deodorant',
    description: 'A gentle aloe-based deodorant that provides effective all-day protection without harsh chemicals.',
    price: 14.99,
    stock: 75,
    category: 'personal-care',
    brand: 'Forever Living',
    form: 'stick',
    tags: ['Aluminum-free', 'Cruelty-free', 'Natural'],
    images: [deodorantImg],
    ingredients: ['Aloe Vera', 'Castor Oil', 'Beeswax', 'Vitamin E'],
    benefits: ['24-hour protection', 'No aluminum', 'Gentle on skin', 'Non-staining'],
    dosage: 'Apply to clean, dry underarms daily.',
    warnings: ['Discontinue use if irritation occurs'],
    allergens: ['Bee products'],
    ratingAvg: 4.7,
    ratingCount: 189,
    createdAt: '2024-01-20',
    isNew: true,
  },
  {
    id: '3',
    name: 'Aloe MSM Gel',
    slug: 'aloe-msm-gel',
    description: 'Soothing relief gel with MSM and aloe vera for tired muscles and joints.',
    price: 24.99,
    discountPrice: 19.99,
    stock: 40,
    category: 'fitness-recovery',
    brand: 'Forever Living',
    form: 'gel',
    tags: ['Vegan', 'Gluten-free', 'Non-greasy'],
    images: [msmGelImg],
    ingredients: ['Aloe Vera Gel', 'MSM', 'Menthol', 'Tea Tree Oil'],
    benefits: ['Soothes muscles', 'Fast-absorbing', 'Non-greasy formula', 'Ideal after workouts'],
    dosage: 'Apply generously to affected areas as needed.',
    warnings: ['For external use only', 'Avoid contact with eyes'],
    allergens: [],
    ratingAvg: 4.9,
    ratingCount: 312,
    createdAt: '2024-02-01',
    isBestseller: true,
  },
  {
    id: '4',
    name: 'Aloe Vera Gelly',
    slug: 'aloe-vera-gelly',
    description: 'Pure aloe vera gel for soothing and moisturizing skin. Perfect for minor skin irritations.',
    price: 18.99,
    stock: 60,
    category: 'skincare',
    brand: 'Forever Living',
    form: 'gel',
    tags: ['100% Stabilized', 'Organic', 'Multi-use'],
    images: [aloeGellyImg],
    ingredients: ['Stabilized Aloe Vera Gel', 'Tocopherol', 'Triethanolamine'],
    benefits: ['Moisturizes skin', 'Soothes irritation', 'Multi-purpose use', 'Fast absorption'],
    dosage: 'Apply liberally to skin as needed.',
    warnings: ['For external use only'],
    allergens: [],
    ratingAvg: 4.8,
    ratingCount: 456,
    createdAt: '2024-02-10',
    isBestseller: true,
  },
  {
    id: '5',
    name: 'Aloe Heat Lotion',
    slug: 'aloe-heat-lotion',
    description: 'Warming massage lotion with aloe vera for soothing relief from aches and tension.',
    price: 22.99,
    stock: 35,
    category: 'fitness-recovery',
    brand: 'Forever Living',
    form: 'lotion',
    tags: ['Warming', 'Natural', 'Deep-penetrating'],
    images: [heatLotionImg],
    ingredients: ['Aloe Vera', 'Menthol', 'Eucalyptus', 'Sesame Oil'],
    benefits: ['Deep warming sensation', 'Relaxes muscles', 'Perfect for massage', 'Long-lasting relief'],
    dosage: 'Massage into skin for soothing warmth.',
    warnings: ['For external use only', 'Wash hands after use'],
    allergens: ['Sesame'],
    ratingAvg: 4.6,
    ratingCount: 178,
    createdAt: '2024-02-15',
  },
  {
    id: '6',
    name: 'Forever Aloe Lips',
    slug: 'forever-aloe-lips',
    description: 'Nourishing lip balm with jojoba and aloe vera for soft, healthy lips.',
    price: 8.99,
    discountPrice: 6.99,
    stock: 100,
    category: 'skincare',
    brand: 'Forever Living',
    form: 'stick',
    tags: ['Moisturizing', 'Natural', 'Portable'],
    images: [aloeLipsImg],
    ingredients: ['Aloe Vera', 'Jojoba Oil', 'Beeswax', 'Vitamin E'],
    benefits: ['Heals dry lips', 'Long-lasting moisture', 'Natural ingredients', 'Compact size'],
    dosage: 'Apply to lips as needed throughout the day.',
    warnings: ['Discontinue if allergic reaction occurs'],
    allergens: ['Bee products'],
    ratingAvg: 4.9,
    ratingCount: 523,
    createdAt: '2024-02-20',
    isBestseller: true,
    isNew: true,
  },
  {
    id: '7',
    name: 'Aloe Moisturizing Lotion',
    slug: 'aloe-moisturizing-lotion',
    description: 'Rich moisturizing lotion with collagen and elastin for youthful, supple skin.',
    price: 28.99,
    stock: 45,
    category: 'skincare',
    brand: 'Forever Living',
    form: 'lotion',
    tags: ['Anti-aging', 'Collagen', 'Hydrating'],
    images: [moisturizingLotionImg],
    ingredients: ['Aloe Vera', 'Collagen', 'Elastin', 'Vitamin E'],
    benefits: ['Deep hydration', 'Improves elasticity', 'Reduces fine lines', 'Silky smooth feel'],
    dosage: 'Apply to face and body after cleansing.',
    warnings: ['For external use only'],
    allergens: [],
    ratingAvg: 4.7,
    ratingCount: 267,
    createdAt: '2024-03-01',
  },
  {
    id: '8',
    name: 'Aloe-Jojoba Conditioner',
    slug: 'aloe-jojoba-conditioner',
    description: 'Nourishing hair conditioner with aloe vera and jojoba for all hair types.',
    price: 19.99,
    stock: 55,
    category: 'hair-care',
    brand: 'Forever Living',
    form: 'liquid',
    tags: ['All hair types', 'Nourishing', 'Natural'],
    images: [conditionerImg],
    ingredients: ['Aloe Vera', 'Jojoba Oil', 'Vitamin B5', 'Wheat Protein'],
    benefits: ['Strengthens hair', 'Adds shine', 'Detangles easily', 'pH-balanced formula'],
    dosage: 'Apply after shampooing, leave for 2-3 minutes, then rinse.',
    warnings: ['Avoid contact with eyes'],
    allergens: ['Wheat'],
    ratingAvg: 4.5,
    ratingCount: 145,
    createdAt: '2024-03-10',
    isNew: true,
  },
  {
    id: '9',
    name: 'Vitamin C Plus',
    slug: 'vitamin-c-plus',
    description: 'High-potency vitamin C tablets with rose hips for immune support.',
    price: 24.99,
    discountPrice: 21.99,
    stock: 80,
    category: 'vitamins',
    brand: 'VitaCare',
    form: 'capsules',
    tags: ['Immune support', 'Antioxidant', 'Vegan'],
    images: [aloeGellyImg],
    ingredients: ['Vitamin C', 'Rose Hips', 'Citrus Bioflavonoids'],
    benefits: ['Boosts immunity', 'Antioxidant protection', 'Supports skin health', 'Natural ingredients'],
    dosage: 'Take 1 tablet daily with food.',
    warnings: ['Do not exceed recommended dose'],
    allergens: [],
    ratingAvg: 4.8,
    ratingCount: 389,
    createdAt: '2024-03-15',
    isBestseller: true,
  },
  {
    id: '10',
    name: 'Omega-3 Fish Oil',
    slug: 'omega-3-fish-oil',
    description: 'Premium omega-3 fatty acids from cold-water fish for heart and brain health.',
    price: 34.99,
    stock: 65,
    category: 'supplements',
    brand: 'VitaCare',
    form: 'capsules',
    tags: ['Heart health', 'Brain support', 'Gluten-free'],
    images: [heatLotionImg],
    ingredients: ['Fish Oil', 'EPA', 'DHA', 'Vitamin E'],
    benefits: ['Supports heart health', 'Brain function', 'Joint flexibility', 'Eye health'],
    dosage: 'Take 2 softgels daily with meals.',
    warnings: ['Consult doctor if on blood thinners'],
    allergens: ['Fish'],
    ratingAvg: 4.6,
    ratingCount: 234,
    createdAt: '2024-03-20',
  },
  {
    id: '11',
    name: 'Probiotic Complex',
    slug: 'probiotic-complex',
    description: 'Multi-strain probiotic for digestive health and immune support.',
    price: 29.99,
    stock: 70,
    category: 'supplements',
    brand: 'VitaCare',
    form: 'capsules',
    tags: ['Gut health', 'Immune support', 'Vegan'],
    images: [moisturizingLotionImg],
    ingredients: ['Lactobacillus', 'Bifidobacterium', 'Prebiotic Fiber'],
    benefits: ['Improves digestion', 'Boosts immunity', 'Reduces bloating', 'Supports gut flora'],
    dosage: 'Take 1 capsule daily on empty stomach.',
    warnings: ['Store in cool, dry place'],
    allergens: [],
    ratingAvg: 4.7,
    ratingCount: 298,
    createdAt: '2024-04-01',
    isNew: true,
  },
  {
    id: '12',
    name: 'Collagen Peptides Powder',
    slug: 'collagen-peptides-powder',
    description: 'Hydrolyzed collagen powder for skin, hair, nails, and joint support.',
    price: 39.99,
    discountPrice: 34.99,
    stock: 40,
    category: 'supplements',
    brand: 'VitaCare',
    form: 'powder',
    tags: ['Beauty', 'Joint support', 'Gluten-free'],
    images: [conditionerImg],
    ingredients: ['Hydrolyzed Bovine Collagen', 'Vitamin C', 'Hyaluronic Acid'],
    benefits: ['Improves skin elasticity', 'Strengthens nails', 'Supports joints', 'Promotes hair growth'],
    dosage: 'Mix 1 scoop with beverage daily.',
    warnings: ['Not suitable for vegetarians'],
    allergens: [],
    ratingAvg: 4.9,
    ratingCount: 412,
    createdAt: '2024-04-10',
    isBestseller: true,
  },
];

export const categories = [
  { id: 'supplements', name: 'Supplements', icon: '💊' },
  { id: 'vitamins', name: 'Vitamins', icon: '🌟' },
  { id: 'skincare', name: 'Skincare', icon: '✨' },
  { id: 'hair-care', name: 'Hair Care', icon: '💇' },
  { id: 'fitness-recovery', name: 'Fitness & Recovery', icon: '💪' },
  { id: 'personal-care', name: 'Personal Care', icon: '🧴' },
];

export const brands = [
  'Forever Living',
  'VitaCare',
];

export const forms = [
  'capsules',
  'powder',
  'gummies',
  'serum',
  'cream',
  'gel',
  'lotion',
  'spray',
  'liquid',
  'stick',
];

export const tags = [
  'Vegan',
  'Organic',
  'Sugar-free',
  'Gluten-free',
  'Cruelty-free',
  'Natural',
  'Aluminum-free',
  'Fluoride-free',
];
